# Generated by Django 4.1.1 on 2022-09-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_alter_item_description_alter_item_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
