# Generated by Django 4.1.1 on 2022-09-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField(blank=True, null=True)),
                ('lastName', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
