# Generated by Django 4.1.1 on 2022-10-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Account",
        ),
    ]
