# Generated by Django 4.1.1 on 2022-10-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_relationship"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.TextField(blank=True),
        ),
    ]
