# Generated by Django 4.1.1 on 2022-10-13 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_remove_profile_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="country",
        ),
    ]
