# Generated by Django 4.1.1 on 2022-10-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_remove_profile_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="profile_pics"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(default="", max_length=300),
        ),
    ]
