# Generated by Django 4.1.1 on 2022-10-25 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_profile_image_alter_profile_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="avatar",
        ),
    ]
